<a href="https://colab.research.google.com/github/ancestor9/Introduction-to-BigData-Analysis/blob/main/13%EC%A3%BC%EC%B0%A8/AdventureSales_03_Basic_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[Tutorial: From Excel workbook to a Power BI report in Microsoft Teams](https://learn.microsoft.com/en-us/power-bi/create-reports/service-from-excel-to-stunning-report)**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
def summary(df):
    analysis_data = []
    for col in df.columns:
        dtype = df[col].dtype
        missing_count = df[col].isnull().sum()
        missing_percentage = missing_count / len(df) * 100
        unique_count = df[col].nunique()
        top_7_values = df[col].value_counts().nlargest(7).index.tolist()
        analysis_data.append([col, dtype, missing_count, missing_percentage, unique_count, top_7_values])
    analysis_df = pd.DataFrame(analysis_data, columns=['Column', 'DataType', 'MissingCount', 'missing_percentage', 'UniqueCount', 'Top7Values'])
    return analysis_df

In [3]:
import pandas as pd

output_drive_path = '/content/drive/MyDrive/데이터분선입문/data'
df = pd.read_csv(output_drive_path+"/processed_adventureworks_sales_data.csv")
df

,Order Quantity,Unit Price,Product Standard Cost,Total Product Cost,Sales Amount,Channel,Sales Order,Sales Order Line,Business Type,Reseller,...,List Price,Model,Subcategory,Category,Date,Full Date,Customer,Region,Country,Group
0,1,2024.994,1898.0944,1898.0944,2024.994,Reseller,SO43659,SO43659 - 1,Value Added Reseller,Better Bike Shop,...,3374.99,Mountain-100,Mountain Bikes,Bikes,2017-07-02,"2017 Jul, 02",Missing,Southeast,United States,North America
1,3,2024.994,1898.0944,5694.2832,6074.982,Reseller,SO43659,SO43659 - 2,Value Added Reseller,Better Bike Shop,...,3374.99,Mountain-100,Mountain Bikes,Bikes,2017-07-02,"2017 Jul, 02",Missing,Southeast,United States,North America
2,1,2024.994,1898.0944,1898.0944,2024.994,Reseller,SO43659,SO43659 - 3,Value Added Reseller,Better Bike Shop,...,3374.99,Mountain-100,Mountain Bikes,Bikes,2017-07-02,"2017 Jul, 02",Missing,Southeast,United States,North America
3,1,2039.994,1912.1544,1912.1544,2039.994,Reseller,SO43659,SO43659 - 4,Value Added Reseller,Better Bike Shop,...,3399.99,Mountain-100,Mountain Bikes,Bikes,2017-07-02,"2017 Jul, 02",Missing,Southeast,United States,North America
4,1,2039.994,1912.1544,1912.1544,2039.994,Reseller,SO43659,SO43659 - 5,Value Added Reseller,Better Bike Shop,...,3399.99,Mountain-100,Mountain Bikes,Bikes,2017-07-02,"2017 Jul, 02",Missing,Southeast,United States,North America
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121248,1,21.980,8.2205,8.2205,21.980,Internet,SO75122,SO75122 - 1,Missing,Missing,...,21.98,Fender Set - Mountain,Fenders,Accessories,2020-06-15,"2020 Jun, 15",Caleb Lal,Canada,Canada,North America
121249,1,8.990,6.9223,6.9223,8.990,Internet,SO75122,SO75122 - 2,Missing,Missing,...,8.99,Cycling Cap,Caps,Clothing,2020-06-15,"2020 Jun, 15",Caleb Lal,Canada,Canada,North America
121250,1,21.980,8.2205,8.2205,21.980,Internet,SO75123,SO75123 - 1,Missing,Missing,...,21.98,Fender Set - Mountain,Fenders,Accessories,2020-06-15,"2020 Jun, 15",Devin Phillips,Canada,Canada,North America
121251,1,159.000,59.4660,59.4660,159.000,Internet,SO75123,SO75123 - 2,Missing,Missing,...,159.00,All-Purpose Bike Stand,Bike Stands,Accessories,2020-06-15,"2020 Jun, 15",Devin Phillips,Canada,Canada,North America
121252,1,8.990,6.9223,6.9223,8.990,Internet,SO75123,SO75123 - 3,Missing,Missing,...,8.99,Cycling Cap,Caps,Clothing,2020-06-15,"2020 Jun, 15",Devin Phillips,Canada,Canada,North America

In [4]:
df.columns

Index(['Order Quantity', 'Unit Price', 'Product Standard Cost',
       'Total Product Cost', 'Sales Amount', 'Channel', 'Sales Order',
       'Sales Order Line', 'Business Type', 'Reseller', 'City',
       'State-Province', 'Country-Region', 'Postal Code', 'SKU', 'Product',
       'Standard Cost', 'Color', 'List Price', 'Model', 'Subcategory',
       'Category', 'Date', 'Full Date', 'Customer', 'Region', 'Country',
       'Group'],
      dtype='object')

In [5]:
# 컬럼명을 복사하여 chatGPT에게 그루핑해달라고 prompt

ordered_columns = [

    # 날짜 정보
    'Date',
    #'Full Date',

    # 고객 및 리셀러 정보
    'Customer', 'Reseller', 'Business Type', 'Group',

    # 제품 정보
    'SKU', 'Product', 'Color', 'Model', 'Subcategory', 'Category',
    'Standard Cost', 'Product Standard Cost', 'List Price', 'Unit Price', 'Total Product Cost',

    # 주문 정보
    'Order Quantity', 'Sales Amount', 'Sales Order', 'Sales Order Line', 'Channel',

    # 지역 정보
    'City', 'State-Province', 'Country-Region', 'Country', 'Region', 'Postal Code',

]

df = df[ordered_columns]

In [6]:
summary(df)

,Column,DataType,MissingCount,missing_percentage,UniqueCount,Top7Values
0,Date,object,0,0.000000,1081,"[2020-06-06, 2020-06-15, 2019-09-05, 2020-06-0..."
1,Customer,object,0,0.000000,18401,"[Missing, Ashley Henderson, Fernando Barnes, C..."
2,Reseller,object,0,0.000000,634,"[Missing, Vigorous Exercise Company, Larger Cy..."
3,Business Type,object,0,0.000000,4,"[Missing, Warehouse, Value Added Reseller, Spe..."
4,Group,object,0,0.000000,3,"[North America, Europe, Pacific]"
5,SKU,object,0,0.000000,266,"[WB-H098, CA-1098, PK-7098, TT-M928, HL-U509-B..."
6,Product,object,0,0.000000,266,"[Water Bottle - 30 oz., AWC Logo Cap, Patch Ki..."
7,Color,object,34144,28.159303,8,"[Black, Red, Yellow, Silver, Blue, Multi, Silv..."
8,Model,object,0,0.000000,107,"[Sport-100, Mountain-200, Road-650, Water Bott..."
9,Subcategory,object,0,0.000000,35,"[Road Bikes, Tires and Tubes, Mountain Bikes, ..."
10,Category,object,0,0.000000,4,"[Accessories, Bikes, Clothing, Components]"
11,Standard Cost,float64,0,0.000000,125,"[1.8663, 13.0863, 486.7066, 0.8565, 1481.9379,..."
12,Product Standard Cost,float64,0,0.000000,125,"[1.8663, 13.0863, 486.7066, 0.8565, 1481.9379,..."
13,List Price,float64,0,0.000000,113,"[4.99, 34.99, 8.99, 782.99, 2.29, 539.99, 53.99]"
14,Unit Price,float64,0,0.000000,275,"[4.99, 34.99, 8.99, 2.29, 469.794, 3.99, 419.4..."
15,Total Product Cost,float64,0,0.000000,1453,"[1.8663, 13.0863, 0.8565, 1.4923, 3.3623, 6.92..."
16,Order Quantity,int64,0,0.000000,41,"[1, 2, 3, 4, 5, 6, 7]"
17,Sales Amount,float64,0,0.000000,1464,"[4.99, 34.99, 8.99, 2.29, 3.99, 21.98, 9.99]"
18,Sales Order,object,0,0.000000,31455,"[SO51721, SO51739, SO51160, SO53465, SO47355, ..."
19,Sales Order Line,object,0,0.000000,121253,"[SO75123 - 3, SO43659 - 1, SO43659 - 2, SO4365..."
20,Channel,object,0,0.000000,2,"[Reseller, Internet]"
21,City,object,0,0.000000,417,"[Missing, Toronto, London, Paris, Montreal, Bu..."
22,State-Province,object,0,0.000000,65,"[Missing, California, Ontario, Texas, Washingt..."
23,Country-Region,object,0,0.000000,7,"[Missing, United States, Canada, France, Unite..."
24,Country,object,0,0.000000,6,"[United States, Canada, Australia, United King..."
25,Region,object,0,0.000000,10,"[Southwest, Canada, Northwest, Australia, Unit..."
26,Postal Code,object,0,0.000000,463,"[Missing, M4B 1V7, M4B 1V5, V6B 3P7, 98104, 75..."

In [7]:
df.loc[:, 'Date'] = pd.to_datetime(df['Date'])  # datetime 형 변환 안전하게

# Select columns with 'object' dtype
category_columns = df.select_dtypes(include='object').columns
for col in category_columns:
    df.loc[:, col] = df[col].astype('category')  # 범주형 안전 변환

In [8]:
summary(df)

/tmp/ipython-input-2-20732698.py:8: FutureWarning: The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`
  top_7_values = df[col].value_counts().nlargest(7).index.tolist()

,Column,DataType,MissingCount,missing_percentage,UniqueCount,Top7Values
0,Date,object,0,0.000000,1081,"[2020-06-06 00:00:00, 2020-06-15 00:00:00, 201..."
1,Customer,object,0,0.000000,18401,"[Missing, Ashley Henderson, Fernando Barnes, C..."
2,Reseller,object,0,0.000000,634,"[Missing, Vigorous Exercise Company, Larger Cy..."
3,Business Type,object,0,0.000000,4,"[Missing, Warehouse, Value Added Reseller, Spe..."
4,Group,object,0,0.000000,3,"[North America, Europe, Pacific]"
5,SKU,object,0,0.000000,266,"[WB-H098, CA-1098, PK-7098, TT-M928, HL-U509-B..."
6,Product,object,0,0.000000,266,"[Water Bottle - 30 oz., AWC Logo Cap, Patch Ki..."
7,Color,object,34144,28.159303,8,"[Black, Red, Yellow, Silver, Blue, Multi, Silv..."
8,Model,object,0,0.000000,107,"[Sport-100, Mountain-200, Road-650, Water Bott..."
9,Subcategory,object,0,0.000000,35,"[Road Bikes, Tires and Tubes, Mountain Bikes, ..."
10,Category,object,0,0.000000,4,"[Accessories, Bikes, Clothing, Components]"
11,Standard Cost,float64,0,0.000000,125,"[1.8663, 13.0863, 486.7066, 0.8565, 1481.9379,..."
12,Product Standard Cost,float64,0,0.000000,125,"[1.8663, 13.0863, 486.7066, 0.8565, 1481.9379,..."
13,List Price,float64,0,0.000000,113,"[4.99, 34.99, 8.99, 782.99, 2.29, 539.99, 53.99]"
14,Unit Price,float64,0,0.000000,275,"[4.99, 34.99, 8.99, 2.29, 469.794, 3.99, 419.4..."
15,Total Product Cost,float64,0,0.000000,1453,"[1.8663, 13.0863, 0.8565, 1.4923, 3.3623, 6.92..."
16,Order Quantity,int64,0,0.000000,41,"[1, 2, 3, 4, 5, 6, 7]"
17,Sales Amount,float64,0,0.000000,1464,"[4.99, 34.99, 8.99, 2.29, 3.99, 21.98, 9.99]"
18,Sales Order,object,0,0.000000,31455,"[SO51721, SO51739, SO51160, SO53465, SO47355, ..."
19,Sales Order Line,object,0,0.000000,121253,"[SO75123 - 3, SO43659 - 1, SO43659 - 2, SO4365..."
20,Channel,object,0,0.000000,2,"[Reseller, Internet]"
21,City,object,0,0.000000,417,"[Missing, Toronto, London, Paris, Montreal, Bu..."
22,State-Province,object,0,0.000000,65,"[Missing, California, Ontario, Texas, Washingt..."
23,Country-Region,object,0,0.000000,7,"[Missing, United States, Canada, France, Unite..."
24,Country,object,0,0.000000,6,"[United States, Canada, Australia, United King..."
25,Region,object,0,0.000000,10,"[Southwest, Canada, Northwest, Australia, Unit..."
26,Postal Code,object,0,0.000000,463,"[Missing, M4B 1V7, M4B 1V5, V6B 3P7, 98104, 75..."

In [16]:
# prompt: Customer를 총 기간 동안 Recency, Frequency, Monetary 기준으로 분석해줘, 주석을 한글로

# 필요한 라이브러리 임포트

import datetime as dt

# Recency, Frequency, Monetary 분석 함수 정의
# df: 분석할 데이터프레임 (반드시 'Customer', 'Date', 'Sales Amount' 컬럼 포함)
def rfm_analysis(df):
  # 분석 종료 날짜 설정 (데이터의 가장 최근 날짜 이후 하루)
  snapshot_date = df['Date'].max() + dt.timedelta(days=1)

  # 고객별 Recency, Frequency, Monetary 계산
  # Recency: snapshot_date 기준 가장 최근 구매일로부터의 경과 일수
  # Frequency: 총 구매 횟수
  # Monetary: 총 구매 금액
  rfm_df = df.groupby('Customer').agg({
      'Date': lambda date: (snapshot_date - date.max()).days, # Recency 계산
      'Sales Order': 'nunique',  # Frequency 계산 (고유한 주문 번호 수)
      'Sales Amount': 'sum'   # Monetary 계산 (총 판매 금액 합계)
  })

  # 컬럼 이름 변경
  rfm_df.rename(columns={'Date': 'Recency',
                         'Sales Order': 'Frequency',
                         'Sales Amount': 'Monetary'}, inplace=True)

  return rfm_df

# RFM 분석 실행
rfm_df = rfm_analysis(df)

# 결과 출력
print("RFM 분석 결과:")
rfm_df

RFM 분석 결과:

                 Recency  Frequency  Monetary
Customer
Aaron Adams          261          1    117.96
Aaron Alexander       32          1     69.99
Aaron Allen          774          1   3399.99
Aaron Baker          127          1   1750.98
Aaron Bryant         172          2    133.96
...                  ...        ...       ...
Zoe Rogers             7          1     39.98
Zoe Sanchez          181          1     76.96
Zoe Sanders          121          1      4.99
Zoe Torres           233          1     14.98
Zoe Watson           146          1     89.46

[18401 rows x 3 columns]

In [17]:
tf = rfm_df.sort_values('Monetary', ascending=False)
tf

                   Recency  Frequency      Monetary
Customer
Missing                  1       3796  8.045060e+07
Jordan Turner           46          9  1.599910e+04
Willie Xu               55          6  1.349006e+04
Nichole Nara            55          5  1.329538e+04
Kaitlyn Henderson       89          5  1.329427e+04
...                    ...        ...           ...
Alex Collins           162          1  2.290000e+00
Abigail Morris         183          1  2.290000e+00
Brad Kumar             116          1  2.290000e+00
Hunter Miller          254          1  2.290000e+00
Dylan Taylor            56          1  2.290000e+00

[18401 rows x 3 columns]

In [22]:
# Recency 값이 클수록 (더 이전에 구매) 낮은 점수를 부여하기 위해 내림차순 정렬 후 순위 할당
rfm_df['R_Score'] = pd.qcut(rfm_df['Recency'], 5, labels=[5, 4, 3, 2, 1])

# Frequency와 Monetary 값이 클수록 높은 점수를 부여하기 위해 오름차순 정렬 후 순위 할당
# Use pd.cut instead of pd.qcut for Frequency and Monetary due to potential duplicate bin edges with qcut
rfm_df['F_Score'] = pd.cut(rfm_df['Frequency'], 5, labels=[1, 2, 3, 4, 5])
rfm_df['M_Score'] = pd.cut(rfm_df['Monetary'], 5, labels=[1, 2, 3, 4, 5])

# RFM 점수 조합 (예: R_Score와 F_Score를 연결)
# M_Score도 포함하여 세 자리 점수 생성
rfm_df['RFM_Score'] = rfm_df['R_Score'].astype(str) + rfm_df['F_Score'].astype(str) + rfm_df['M_Score'].astype(str)

# 결과 출력
print(rfm_df.head())
print(rfm_df.describe())

# RFM 점수별 고객 세그먼트 정의 예시 (간단한 예시)
# 예: 555는 최고의 고객 (Champions), 111은 이탈 가능성이 높은 고객 (Lost)
# 실제 세그멘테이션은 비즈니스 목표에 따라 다르게 정의될 수 있습니다.

# RFM 세그먼트 예시 (추가적인 분석 및 시각화를 위해 세그먼트 컬럼 생성)
# 예시로 R과 F 점수를 조합하여 세그먼트 생성 (M도 고려 가능)
def segment_me(rfm):
    if rfm['R_Score'] == 5 and rfm['F_Score'] == 5:
        return 'Champions'
    elif rfm['R_Score'] == 5 and rfm['F_Score'] == 4:
        return 'Loyal Customers'
    elif rfm['R_Score'] == 4 and rfm['F_Score'] == 5:
         return 'Potential Loyalists'
    elif rfm['R_Score'] == 5 and rfm['F_Score'] == 1:
        return 'New Customers'
    elif rfm['R_Score'] == 4 and rfm['F_Score'] == 4:
        return 'Promising'
    elif rfm['R_Score'] == 3 and rfm['F_Score'] == 3:
        return 'Need Attention'
    elif rfm['R_Score'] == 2 and rfm['F_Score'] == 2:
        return 'At Risk'
    elif rfm['R_Score'] == 1 and rfm['F_Score'] == 1:
        return 'Lost'
    else:
        return 'Others'

rfm_df['Segment'] = rfm_df.apply(segment_me, axis=1)

                 Recency  Frequency  Monetary R_Score F_Score M_Score  \
Customer
Aaron Adams          261          1    117.96       2       1       1
Aaron Alexander       32          1     69.99       5       1       1
Aaron Allen          774          1   3399.99       1       1       1
Aaron Baker          127          1   1750.98       3       1       1
Aaron Bryant         172          2    133.96       3       1       1

                RFM_Score        Segment
Customer
Aaron Adams           211         Others
Aaron Alexander       511  New Customers
Aaron Allen           111           Lost
Aaron Baker           311         Others
Aaron Bryant          311         Others
            Recency     Frequency      Monetary
count  18401.000000  18401.000000  1.840100e+04
mean     175.323732      1.709418  5.967571e+03
std      145.434223     27.994593  5.930656e+05
min        1.000000      1.000000  2.290000e+00
25%       71.000000      1.000000  4.997000e+01
50%      153.000000      1.000000  2.877000e+02
75%      249.000000      2.000000  2.518250e+03
max     1081.000000   3796.000000  8.045060e+07

In [23]:

# 세그먼트별 고객 수 확인
print("\n고객 세그먼트별 분포:")
rfm_df['Segment'].value_counts()

고객 세그먼트별 분포:

Segment
Others           11066
New Customers     3685
Lost              3649
Champions            1
Name: count, dtype: int64

In [24]:

# 세그먼트별 평균 RFM 값 확인
print("\n세그먼트별 평균 RFM 지표:")
rfm_df.groupby('Segment')[['Recency', 'Frequency', 'Monetary']].mean()

세그먼트별 평균 RFM 지표:

                  Recency    Frequency      Monetary
Segment
Champions        1.000000  3796.000000  8.045060e+07
Lost           378.428611     1.237873  1.585659e+03
New Customers   29.232836     1.800543  1.440878e+03
Others         157.014459     1.491686  1.650368e+03