<a href="https://colab.research.google.com/github/ancestor9/Introduction-to-BigData-Analysis/blob/main/13%EC%A3%BC%EC%B0%A8/data_preprocessing_visualization_statistics_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **텍스트 전처리**

# **기술통계 분석**

In [ ]:
#  나의 드라이브를 마운트 해줘
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Define the path to the data directory in Google Drive
drive_data_path = '/content/drive/MyDrive/데이터분석입문/data'

import pandas as pd

df = pd.read_pickle(drive_data_path + '/df_cleaned.pkl')

In [ ]:
df

,Rental_Date,Rental_Station,Rental_Type_Code,Gender,Age_Group,Rental_Count,Exercise_Amount,Carbon_Amount,Distance_M,Duration_Minutes,days
236013,2024-12-05,442.서울역 서부,일일권,F,30.0,1,15.96,0.14,620.00,5,Thursday
404498,2024-12-09,660. 동의보감타워,정기권,F,50.0,1,12.17,0.15,640.00,7,Monday
599230,2024-12-12,398. 을지로3가역 3번출구,정기권,M,20.0,1,26.55,0.22,957.67,5,Thursday
759406,2024-12-16,143. 공덕역 2번출구,정기권,M,40.0,1,31.81,0.25,1071.04,9,Monday
218405,2024-12-05,1226. 잠실4동 주민센터 옆,정기권,F,30.0,3,50.63,0.52,2268.26,24,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
1183410,2024-12-26,2104. 사당역 5번출구,정기권,M,40.0,1,167.66,1.28,5498.46,39,Thursday
174230,2024-12-04,3523. 건국대학교 과학관(이과대) 앞,정기권,M,40.0,1,64.33,0.48,2056.31,12,Wednesday
808455,2024-12-17,5333. 노원역9번-10번 출구 앞,정기권,M,40.0,1,75.91,0.49,2130.00,16,Tuesday
221279,2024-12-05,1135. 강서구의회,정기권,F,60.0,1,41.32,0.37,1605.09,8,Thursday
351352,2024-12-07,4864. 송파사거리,정기권,M,30.0,1,12.08,0.11,469.39,6,Saturday

### 공원, 역, 사거리, 대학교 근처 장소를 중심으로 분석

In [ ]:
# Rental_Station 컬럼에서 공원, 역, 사거리, 대학교 등의 text가 포함되었는지 여부를 특성 컬럼으로 만들어줘

df['Is_Park'] = df['Rental_Station'].str.contains('공원')
df['Is_Station'] = df['Rental_Station'].str.contains('역')
df['Is_Intersection'] = df['Rental_Station'].str.contains('사거리')
df['Is_University'] = df['Rental_Station'].str.contains('대학교')

display(df.head())

,Rental_Date,Rental_Station,Rental_Type_Code,Gender,Age_Group,Rental_Count,Exercise_Amount,Carbon_Amount,Distance_M,Duration_Minutes,days,Is_Park,Is_Station,Is_Intersection,Is_University
236013,2024-12-05,442.서울역 서부,일일권,F,30.0,1,15.96,0.14,620.00,5,Thursday,False,True,False,False
404498,2024-12-09,660. 동의보감타워,정기권,F,50.0,1,12.17,0.15,640.00,7,Monday,False,False,False,False
599230,2024-12-12,398. 을지로3가역 3번출구,정기권,M,20.0,1,26.55,0.22,957.67,5,Thursday,False,True,False,False
759406,2024-12-16,143. 공덕역 2번출구,정기권,M,40.0,1,31.81,0.25,1071.04,9,Monday,False,True,False,False
218405,2024-12-05,1226. 잠실4동 주민센터 옆,정기권,F,30.0,3,50.63,0.52,2268.26,24,Thursday,False,False,False,False

In [ ]:
# 추가된  특성컬럼별로 Rental_Count의 합계를 구해줘

rental_count_by_location_type = df[['Is_Park', 'Is_Station', 'Is_Intersection', 'Is_University', 'Rental_Count']].groupby(['Is_Park', 'Is_Station', 'Is_Intersection', 'Is_University']).sum()

display(rental_count_by_location_type)

                                                  Rental_Count
Is_Park Is_Station Is_Intersection Is_University
False   False      False           False                   648
                                   True                     15
                   True            False                    49
        True       False           False                   333
                   True            False                     2
True    False      False           False                    39
        True       False           False                     9

## **정규표현식(regular expression)**

In [ ]:
# 정규표현식(regular expression)을 학습하려고해 예제 코드를 제시해줘

import re

# Example string
text = "The quick brown fox jumps over the lazy dog. 12345"

In [ ]:
# 1. Basic matching
# Find all occurrences of "the" (case-insensitive)
matches_the = re.findall(r"the", text, re.IGNORECASE)
print(f"Occurrences of 'the': {matches_the}")

Occurrences of 'the': ['The', 'the']

In [ ]:

# 2. Matching digits
# Find all digits
matches_digits = re.findall(r"\d", text)
print(f"Digits: {matches_digits}")

Digits: ['1', '2', '3', '4', '5']

In [ ]:

# 3. Matching words
# Find all words (sequences of letters)
matches_words = re.findall(r"\b[a-zA-Z]+\b", text)
print(f"Words: {matches_words}")

Words: ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

In [ ]:

# 4. Matching specific patterns
# Find a sequence of 5 digits
match_five_digits = re.search(r"\d{5}", text)
if match_five_digits:
    print(f"Five consecutive digits found: {match_five_digits.group()}")

Five consecutive digits found: 12345

In [ ]:

# 5. Replacing patterns
# Replace spaces with hyphens
text_replaced = re.sub(r"\s", "-", text)
print(f"Text with spaces replaced: {text_replaced}")

Text with spaces replaced: The-quick-brown-fox-jumps-over-the-lazy-dog.-12345

In [ ]:

# 6. Splitting strings
# Split the string by spaces
split_text = re.split(r"\s", text)
print(f"Split text: {split_text}")

Split text: ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog.', '12345']