<a href="https://colab.research.google.com/github/ancestor9/Introduction-to-BigData-Analysis/blob/main/7%EC%A3%BC%EC%B0%A8/pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Getting started tutorials**
- **What kind of data does pandas handle?**
- **How do I read and write tabular data?**
- **How do I select a subset of a DataFrame?**

    - How do I create plots in pandas?
    - How to create new columns derived from existing columns
    - How to calculate summary statistics
    - How to reshape the layout of tables
    - How to combine data from multiple tables
    - How to handle time series data with ease
    - How to manipulate textual data

## 1. What kind of data does pandas handle?
### pandas data table representation
- **DataFrame는 column과 row로 구성**
<img src ='https://pandas.pydata.org/docs/_images/01_table_dataframe.svg'>

In [1]:
import pandas as pd

In [3]:
data = {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }

In [5]:
df = pd.DataFrame(data)
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [9]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

In [8]:
type(df['Age'])

pandas.core.series.Series

In [7]:
ages = pd.Series([22, 35, 58], name="Age")
ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [10]:
type(ages)

pandas.core.series.Series

In [11]:
df["Age"].max()

58

In [12]:
ages.min()

22

In [13]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

## **2. How do I read and write tabular data?**

<img src='https://pandas.pydata.org/docs/_images/02_io_readwrite.svg'>

In [20]:
# prompt: fake 를 사용하여 100개의 name, age, salary, address, email, telephone 을  데이터프레임으로 만들어줘

import pandas as pd
!pip install faker -q
from faker import Faker
fake = Faker()

data = {
    "Name": [fake.name() for _ in range(100)],
    "Age": [fake.random_int(min=18, max=90) for _ in range(100)],
    "Salary": [fake.random_int(min=20000, max=100000) for _ in range(100)],
    "Address": [fake.address() for _ in range(100)],
    "Email": [fake.email() for _ in range(100)],
    "Telephone": [fake.phone_number() for _ in range(100)],
}

df = pd.DataFrame(data)
df

,Name,Age,Salary,Address,Email,Telephone
0,Gabriel Moore,50,93998,"1369 Marcia Road Apt. 226\nSouth Mark, FM 15965",bryan44@example.com,+1-224-222-1431
1,Susan Garrett,51,33669,"980 Hart Stravenue\nDarrenfurt, SD 81974",monica70@example.com,583-725-7022
2,Dominique Rodriguez,19,30201,"73270 Lauren Way Suite 467\nCuevasshire, KS 92617",jbrock@example.org,200-226-4035x2753
3,Kayla Montgomery,39,65465,"5172 Campbell Well\nDeborahchester, NY 64537",michael49@example.net,7339528350
4,Deborah Castro,53,35141,"192 Katherine Mission\nSouth Tyler, OR 04440",omiller@example.com,+1-713-452-3143x627
...,...,...,...,...,...,...
95,Melinda Clark,18,27475,"4902 Kristopher Path\nEast Alyssahaven, AZ 73361",vwilliams@example.net,001-687-756-3985x7116
96,Krista Torres,30,46929,"75887 Combs Avenue\nWest Deannaville, AK 99163",williamwilliams@example.org,9527566348
97,Brittany Mays,33,37698,"875 Wagner Hollow\nSeanshire, IA 85688",mwiley@example.com,519-833-4669
98,Lindsey Meadows,44,70770,"5401 Dustin Rapid\nLarryhaven, TN 17920",justincoleman@example.org,+1-655-574-9586x06060
99,James Cox,49,28923,"5864 Velez Harbor\nPort Alexanderbury, FM 59650",michaelahill@example.com,(847)435-1750x9760

In [35]:
# prompt: df DataFrame 사용: 엑셀로 저장해줘

# Save the DataFrame to an Excel file named 'output.xlsx'
df.to_excel('output.xlsx')

In [36]:
# prompt: /content/output.xlsx 을 읽어줘

# Read the Excel file 'output.xlsx' into a DataFrame
df = pd.read_excel('/content/output.xlsx')

In [37]:
df.head()

,Unnamed: 0,Name,Age,Salary,Address,Email,Telephone
0,0,Gabriel Moore,50,93998,"1369 Marcia Road Apt. 226\nSouth Mark, FM 15965",bryan44@example.com,+1-224-222-1431
1,1,Susan Garrett,51,33669,"980 Hart Stravenue\nDarrenfurt, SD 81974",monica70@example.com,583-725-7022
2,2,Dominique Rodriguez,19,30201,"73270 Lauren Way Suite 467\nCuevasshire, KS 92617",jbrock@example.org,200-226-4035x2753
3,3,Kayla Montgomery,39,65465,"5172 Campbell Well\nDeborahchester, NY 64537",michael49@example.net,7339528350
4,4,Deborah Castro,53,35141,"192 Katherine Mission\nSouth Tyler, OR 04440",omiller@example.com,+1-713-452-3143x627

In [38]:
# prompt: df DataFrame 사용: Unnamed: 0 은 제거해줘

# Drop the 'Unnamed: 0' column from the dataframe
df = df.drop('Unnamed: 0', axis=1)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Age        100 non-null    int64
 2   Salary     100 non-null    int64
 3   Address    100 non-null    object
 4   Email      100 non-null    object
 5   Telephone  100 non-null    object
dtypes: int64(2), object(4)
memory usage: 4.8+ KB

In [40]:
df.describe()

              Age        Salary
count  100.000000    100.000000
mean    54.370000  55771.870000
std     21.244443  20655.826748
min     18.000000  20499.000000
25%     39.000000  37398.000000
50%     51.000000  54412.500000
75%     75.250000  70803.750000
max     89.000000  98467.000000

## **3. How do I select a subset of a DataFrame?**
### **3.1. How do I select specific columns from a DataFrame?**

<img src='https://pandas.pydata.org/docs/_images/03_subset_columns.svg'>

In [41]:
# prompt: seabeorn 에서 titanic을 읽어줘

import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [43]:
titanic.shape

(891, 15)

In [42]:
ages = titanic["age"]
ages

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [44]:
ages.shape

(891,)

In [45]:
age_sex = titanic[["age", "sex"]]
age_sex

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [46]:
type(age_sex)

pandas.core.frame.DataFrame

In [47]:
age_sex.shape

(891, 2)

### **3.3. How do I filter specific rows from a DataFrame?**

In [49]:
above_35 = titanic[titanic["age"] > 35]
above_35

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False

In [50]:
titanic["age"] > 35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [51]:
above_35.shape

(217, 15)

In [52]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [53]:
titanic["pclass"].unique()

array([3, 1, 2])

In [54]:
titanic["pclass"].isin([2, 3])

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: pclass, Length: 891, dtype: bool

In [55]:
class_23 = titanic[titanic["pclass"].isin([2, 3])]
class_23

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [57]:
titanic[(titanic["pclass"] == 2) | (titanic["pclass"] == 3)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [63]:
titanic[(titanic["pclass"] == 3) & (titanic["age"] > 45)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
94,0,3,male,59.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
132,0,3,female,47.0,1,0,14.5000,S,Third,woman,False,NaN,Southampton,no,False
152,0,3,male,55.5,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
203,0,3,male,45.5,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
222,0,3,male,51.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
280,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
326,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
406,0,3,male,51.0,0,0,7.7500,S,Third,man,True,NaN,Southampton,no,True
482,0,3,male,50.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
483,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
592,0,3,male,47.0,0,0,7.2500,S,Third,man,True,NaN,Southampton,no,True
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
631,0,3,male,51.0,0,0,7.0542,S,Third,man,True,NaN,Southampton,no,True
736,0,3,female,48.0,1,3,34.3750,S,Third,woman,False,NaN,Southampton,no,False
771,0,3,male,48.0,0,0,7.8542,S,Third,man,True,NaN,Southampton,no,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True

In [64]:
len(titanic[(titanic["pclass"] == 3) & (titanic["age"] > 45)])

18

In [66]:
len(titanic[(titanic["pclass"] == 3) & (titanic["age"] > 45) & (titanic["alive"] == "yes")])

1

In [68]:
1/18*100

5.555555555555555

In [74]:
for i in range(1, 4):
    a = len(titanic[(titanic["pclass"] == i) & (titanic["age"] > 45)])
    b = len(titanic[(titanic["pclass"] == i) & (titanic["age"] > 45) & (titanic["alive"] == "yes")])
    print(f'{i} class의 생존율은 {b/a*100:.2f}%')

1 class의 생존율은 48.39%
2 class의 생존율은 30.43%
3 class의 생존율은 5.56%

In [75]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [76]:
age_no_na = titanic[titanic["age"].notna()]
age_no_na

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [77]:
titanic.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [78]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### **3.3. How do I select specific rows and columns from a DataFrame?**

<img src ='https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg'>

In [79]:
titanic.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [82]:
adult_fare = titanic.loc[titanic["age"] > 45, "fare"]
adult_fare

6      51.8625
11     26.5500
15     16.0000
33     10.5000
52     76.7292
        ...
857    26.5500
862    25.9292
871    52.5542
873     9.0000
879    83.1583
Name: fare, Length: 103, dtype: float64

In [83]:
titanic.iloc[9:25, 2:5]

       sex   age  sibsp
9   female  14.0      1
10  female   4.0      1
11  female  58.0      0
12    male  20.0      0
13    male  39.0      1
14  female  14.0      0
15  female  55.0      0
16    male   2.0      4
17    male   NaN      0
18  female  31.0      1
19  female   NaN      0
20    male  35.0      0
21    male  34.0      0
22  female  15.0      0
23    male  28.0      0
24  female   8.0      3

In [86]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [85]:
titanic.iloc[0:3, 3]

0    22.0
1    38.0
2    26.0
Name: age, dtype: float64

In [87]:
titanic.iloc[0:3, 3] = 999
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,999.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,999.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,999.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True